== Getting Started

All of this is subject to change, but if you want to try to run the
project right now, then this should help you get going.

=== Running inside nodejs

Requirements: Nodejs >=18 (we need parseArgs)

There’s a `main.mjs` for Node.js which can drop you into a REPL, or can
load and run files or modules you give it.

[source,shell]
----
node lib/piglet/node/main.mjs
----

The `bin/piglet` script does the same, but with some added conveniences.

* Resolves the path to `node/main.mjs` based on the location of the
script, so you can call it from anywhere
* Calls piglet with `rlwrap`, so you get REPL history and editing
* Adds a `--devtools` flag (see below)

You should symlink `bin/piglet` to somewhere on your `$PATH`, so you can
just invoke piglet from anywhere with `piglet`. What follows assumes you
have that done

Command line flags:

* `-p`: load a package given a path of a directory containing a
`package.pig` file. Does not load any actual code, but allows importing
modules from the package with `-i` or from code. Alternatively use
`:pkg:deps` in `package.edn`
* `-i`: import a module, using `package:module`,
e.g. `-i piglet:pdp-client` or `-i https://example.com/my-pkg:my-mod`
* `-v`: inrease verbosity, when using the REPL this will print out
intermediate steps in the evaluation, like the form, generated JS code,
or AST

You can also pass positional arguments, which should be paths to `.pig`
script files. These will be evaluated in order.

==== Connecting from Chrome devtools

While working on Piglet itself `piglet --devtools` is very handy. Note
that `--devtools` has to be the first argument to `piglet`, since it’s
processed by the wrapper script, not by piglet itself. So if you are
passing additional arguments to Piglet, then add those at the end.

This will invoke node with the `--inspect` flag, which allows you to
connect from your Chrome devtools, and will run with
https://www.npmjs.com/package/nodemon[nodemon] which provides hot reload
(of Piglet’s own code, we don’t yet have hot reload for your Piglet
code).

==== Connecting to a PDP server

PDP stands for Piglet Dev Protocol, and is what is used for
communication between your editor and Piglet when doing interactive
programming. You may be used to languages where your editor connects to
a REPL. With PDP these roles are reversed, your editor provides the
server, and Piglet connects to it.

Currently there is only a PDP implementation for Emacs, found in
https://github.com/piglet-lang/piglet-emacs[piglet-emacs] :
https://github.com/piglet-lang/piglet-emacs/blob/main/pdp.el[pdp.el].
See below for setting up Emacs.

=== Running in the browser

Piglet itself is written to run in the browser from source without any
additional tooling or compilation, you just need something to serve up the files
over HTTP. The easiest way to get started is by using the jsDeliver CDN, which
will pull files from the npm release:

[source,html]
----
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="importmap">
      {"imports": {"astring": "https://cdn.jsdelivr.net/npm/astring@latest/dist/astring.mjs"}}
    </script>
    <script type="module" src="https://cdn.jsdelivr.net/npm/piglet-lang@0.0.19/lib/piglet/browser/main.mjs"></script>
    <script type="piglet">
      (js:console.log "Hello from Piglet 🐷!")
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
----

The `piglet/browser/main.mjs` entry point will run any `script` tags it finds
with type="piglet". They can be inline scripts like the one above, or reference
a file to load with `src="..."`.

Notice the `importmap`, this is standard browser feature, not anything Piglet
related. Piglet requires `astring` to convert JS AST (known as ESTree), to JS.
When we `import "astring"` the browser needs to know where `astring` is supposed
to come from. In Node.js there's automatic resolution based on `node_modules`,
in the browser you use `importmap` to specify a URL.

You can use `importmap` to make other JS libraries available as well, which you
can then import with a simple short name.

[source,html]
----
<script type="importmap">
  {"imports":
   {"astring": "https://cdn.jsdelivr.net/npm/astring@latest/dist/astring.mjs",
    "solid-js": "https://cdn.jsdelivr.net/npm/solid-js@latest/dist/solid.js"}}
</script>
<script type="module" src="https://cdn.jsdelivr.net/npm/piglet-lang@latest/lib/piglet/browser/main.mjs"></script>
<script type="piglet">
  (module main
   (:import [solid :from "solid-js"]))

  (js:console.log (js:Object.keys (.-vars (find-module 'solid))))
</script>
----

To load JS files that are included in your own package, use relative paths:
`(:import [util :from "util.js"])`. Note that these have to be valid ES6
modules.

Using `<script type="piglet">` will evaluate the given code (inline or from a
file) as scripts, simply evaluating forms from top to bottom. If you want to
bundle a bunch of modules in a package, and/or load modules from other packages,
then point piglet first at the package location, which contains its
`package.pig`

Say you have the following `package.pig` at `http://example.com/my/pkg/package.pig`:

[source,piglet]
----
{:pkg:name https://packages.example.com/my-pkg
 :pkg:paths ["src"]}
----

And a module at `http://example.com/my/pkg/src/main.pig`.

Then you could load it with:

[source,html]
----
<script type="piglet">
  ;; Load //example.com/my/pkg/package.pig
  (load-package "//example.com/my/pkg")
  ;; Load the module
  (require 'https://packages.example.com/my-pkg:main)
</script>
----

Your package can in turn depend on other packages, which will get loaded and
resolved too.

A piglet web project could look like this:

[source]
----

.
├── index.html
├── package.pig
└── src
    └── main.pig
----

Where from `index.html` you do `(load-package js:window.location)`, and then
continue to require your main module.

The `http-server` package can be useful here.

[source,shell]
----
pnpm i http-server -g
http-server --port 8000 --cors
----

==== Source Maps

The BrowserCompiler is able to generate source maps, which are inlined into the evaluated code. To enable this, make sure the `source-map` library is loaded.

[source,html]
----
<script type="application/javascript" src="https://unpkg.com/source-map@0.7.3/dist/source-map.js"></script>
----

=== Setting up Emacs

Requirements: Emacs 29 compiled with tree-sitter.

Piglet has a https://tree-sitter.github.io/tree-sitter/[tree-sitter]
grammar, which any editor integration SHOULD use. This ensures that all
editors have a consistent way of parsing and handling piglet code.
Tree-sitters grammars are easy to define, and the generated parsers are
very fast and can be used in many contexts, either by compiling to
C/Rust or to WASM.

Most editors have tree-sitter integration, and defining e.g. indentation
or syntax highlighting based on a tree-sitter grammar is usually much
easier than doing it with an editor’s native language handling support.

Emacs’s has tree-sitter support since Emacs 29, which is not (at time of
writing) officially out yet, so you need to build it yourself, and you
need to make sure that it gets compiled with tree-sitter enabled.

For Debian/Ubuntu based distros, install `libtree-sitter0` (and possibly
also `libtree-sitter-dev`).

[source,shell]
----
git clone https://github.com/emacs-mirror/emacs
cd emacs
git co emacs-29
./autogen.sh
./configure --with-tree-sitter
# (you can add more flags here, like --with-native-compilation)
make -j4
# replace 4 with the number of cores you have
sudo make install
----

Now you need to set up piglet-emacs, which contains the `piglet-mode`
major mode, and a PDP (piglet dev protocol) server implementation.

If you are using the
https://github.com/radian-software/straight.el[Straight] package manager
for Emacs then you can get `piglet-emacs` from Corgi’s package
repository (you don’t need to use any other part of Corgi). For
instance:

[source,emacs-lisp]
----
;; ... bootstrap straight ...

(straight-use-package 'use-package)

(setq straight-use-package-by-default t)

(use-package corgi-packages
  :straight (corgi-packages
             :type git
             :host github
             :repo "corgi-emacs/corgi-packages"))
             
(use-package piglet-emacs)
----

Open a `.pig` file and you should see syntax highlighting and have
indentation support. Congrats!

==== Emacs PDP server

For interactive programming you start a PDP server inside Emacs (this is
a http server listening for websocket connections), then connect to it
from Piglet.

....
M-x pdp-start-server!
....

Now start piglet with `piglet -i piglet:pdp-client`, and you should see
a (noisy) message in your minibuffer. Now you can use

- `pdp-eval-last-sexp`
- `pdp-eval-outer-sexp`
- `pdp-eval-buffer`
- `pdp-eval-region`
- `pdp-jump-to-definition`

Note that jump-to-definition is a standalone command, not backed by Xref, but we
do push a marker onto xref's marker stack before jumping, so you can jump back
as you are used to. When using piglet on a web project you can enable the
`url-handler-mode` globalized minor mode, to make Emacs load files over the HTTP
when jumping to definition. (In such a scenario the `:location` metadata on the
var is a URL, rather than a filename.)

Note that you can open a file and do a `pdp-eval-buffer` to have all vars
in that module reflect the location as reported by Emacs.

PDP messages carry the current package, module, buffer-file-name, source
location, etc. This ensures that when you eval a form in a module's buffer, it's
evaluated in that module, not whatever module is currently active or most
recently loaded. We don't auto-eval module declarations though, so if you have
any imports you will have to eval the module form before those are available.

Reporting the filename and source location ensures that var metadata is correct,
which in turn ensures that jump-to-definition can do its job.

=== Creating your first project

[source,shell]
----
mkdir my-proj
cd my-proj
cat <<EOF > package.pig
{:pkg:name https://example.com/my-pkg
 :pkg:paths ["src"]
 :pkg:deps {}}
EOF

mkdir src
echo '(module hello) (println "Working!")' > src/hello.pig
----

[source,shell]
----
piglet -i hello
# or
piglet -i https://example.com/my-pkg:hello
----

=== Declaring dependencies

Currently we can only handle dependencies that exist as packages on the
local filesystem. For this the syntax in `package.pig` is

[source,piglet]
----
{:pkg:deps {some-alias {:pkg:location "../other-package-dir"}}}
----

This assumes that there’s a `package.pig` in `../other-package-dir`.
With this in place you can start importing modules from this other
package in your modules, using the `some-alias` alias.

[source,piglet]
----
(module hello
  (:import
    [m :as some-alias:some-module]))
----

You can also ignore the alias, and use a full identifier. So say
`other-package-dir/package.pig` contains
`{:pkg:name https://example.com/other-package}`:

[source,piglet]
----
(module hello
  (:import
    [m :as https://example.com/other-package:some-module]))
----
