= JavaScript integration

Piglet tries its best to make modern JavaScript features conveniently available.

== Literals

The `#js` reader dispatch causes the compiler to emit JavaScript literals,
either Arrays or Objects.

[source,piglet]
-------------------
#js [1 2 3]
#js {:foo 1 :bar 2}
-------------------

Note that `#js` is not recursive, if you need nested JS arrays/objects, you need
to prefix each of them. Otherwise you'll end up with Piglet datasctructures
(Vector, Dict) inside your JS Arrays/Objects.

[source,piglet]
-------------------
#js [#js {:sound "Oink"}]
-------------------

== Calling functions and looking up properties

The `js:` prefix is considered special, symbols with this prefix are converted
directly to JavaScript names.

[source,piglet]
-------------------
(js:String "hello")
-------------------

You can chain property lookups directly onto this:

[source,piglet]
-------------------
(js:console.log "hello")
(js:window.document.createElement "div") 
-------------------

A symbol starting with a period is converted to a method call:

[source,piglet]
-------------------
(.appendChild el child) 
-------------------

A symbol starting with `.-` does a property lookup, rather than a function
invocation.

[source,piglet]
-------------------
(.-oink #js {:oink "OINK"})
(.-length "xxx")
-------------------

Note that this is a low-level way of accessing properties, which will always do
a simple JS object property lookup. Generally you can look up properties in JS
objects the same way you do in Piglet dictionaries.

[source,piglet]
-------------------
(:oink #js {:oink "OINK"})
(get {:oink "OINK"} :oink)
-------------------

== Manipulating data

Generally working with JS collections (arrays and objects, Set and Map
instances), you can simply use the same functions you use with Piglet
collections like dictionaries and lists.

- `conj`
- `assoc`
- `dissoc`
- `into`
- `get`
- `get-in`
- `assoc-in`
- `update`
- `update-in`

But note that these are all pure functions, they don't change the collection you
pass them, but instead create a new one. In other words: they need to copy over
the entire collection each time you call them. This means that update and insert
operations will get slower the more elements there are in the collection. This
isn't so much a concern with Piglet's data structures since those are designed
so we don't need to copy the entire collection (or at least they will be once we
get around to it).

We also have versions of these functions that do change the collection
"in-place".

- `conj!`
- `assoc!`
- `dissoc!`
- `into!`
- `assoc-in!`
- `update!`
- `update-in!`

[source,piglet]
-------------------
(let [x #js {}]
  (assoc-in! x [:x :y] 1)
  (update-in! x [:x :y] inc)
  x)
=> #js {:x #js {:y 2}}
-------------------

== Protocol support

JavaScript built-ins like Arrays, Objects, but also Map instances, ArrayBuffer,
Uint8/32/64Array, etc. all implement one or more Piglet protocols, which means
they can be used directly with many of Piglet's core functions.

At a minimum these all implement Seqable, which means you can generally treat
them as a sequential collection. So you can call functions like `first` or `map`
on them, and they can take part in destructuring.

Arrays can be destructured.

[source,piglet]
-------------------
(let [[x y] #js [1 2]] (+ x y))
(map (fn [[k v]] (str k "--" v)) #js {:foo 1})
=> ("foo--1")
-------------------

Conversely, all Piglet datastructures implement Symbol.iterator. So you can
generally use them in JavaScript functions that take some kind of iterable
collection.

[source,piglet]
-------------------
(js:Map. {"hello" "world"})

(js:Array.from (range 5))
;; #js [0, 1, 2, 3, 4]
-------------------

== Working with promises

Functions can be marked as async, and there's an await special form

[source,piglet]
-------------------
(defn ^:async my-fn []
  (await (js:fetch "...")))
-------------------

For loops also support `^:async`, the result is a promise to a seq.

[source,piglet]
-------------------
(for ^:async [url ["http://example.com"]]
  (js:fetch url))
-------------------


